name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.2.1
        with:
          hugo-version: '0.152.0' # 🎯 ON ALIGNE SUR TON LOCAL
          extended: true

      # ÉTAPE DE SÉCURITÉ : On s'assure que Hugo reconnaît le dossier comme un module
      - name: Initialize Hugo Mod (if missing)
        run: |
          if [ ! -f go.mod ]; then
            hugo mod init github.com/oufoke/portofolio-oumar
          fi

      - name: Build
        run: hugo --minify --gc --enableGitInfo # --gc nettoie les vieux fichiers

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public